export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";
export const INCREASE_ITEM_FROM_CART = "INCREASE_ITEM_FROM_CART";
export const DECREASE_ITEM_FROM_CART = "DECREASE_ITEM_FROM_CART";
export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const CLEAR_ITEM_FROM_CART = "CLEAR_ITEM_FROM_CART";
